MONGO_URI = "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/"
MONGO_DB = "dataset_airbnb"
MONGO_COLLECTION = "dads_dataset"

SNOWFLAKE_USER = "your_username"
SNOWFLAKE_PASSWORD = "your_password"
SNOWFLAKE_ACCOUNT = "ap-southeast-7.aws-qv19603"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "AIRBNB_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
