# .streamlit/secrets.toml
#share file googlesheet to public and clear catch on streamlit


[mongo]
uri = "mongodb+srv://gipfee33333:Ox3354xo@cluster0.wgt15cd.mongodb.net/?appName=Cluster0"
db_name = "sample_airbnb"